version: '3.5'
services:
  tools:
    build:
      context: ./
      dockerfile: Dockerfile.tools
    command: tail -f /dev/null

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    networks:
      zabbix_network:
        ipv4_address: 172.19.0.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - ./usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      DB_SERVER_HOST: mydatabase.v41.me
      MYSQL_USER: jtxZ3A9A69J2eFgVwp_zabbix
      MYSQL_PASSWORD: jtxZ3A9A69J2eFgVwpJE97beUnuE9MW5xBerSgSaespwrTEYx5qbKgLsNfJqRSXHtmfpHh
      MYSQL_ROOT_PASSWORD: ZubRfFzeEN&T#^LHmJRkWN96Lf^ZxpL_8tcGT@ntV7S4Rha?UaVpT#CjcC7GgGT&!aq?wA?4q*cKDxr
      MYSQL_DATABASE: K9brEwbDsdxtMyGAXV_zabbix
      ZBX_JAVAGATEWAY_ENABLE: 'false'
      ZBX_ENABLE_SNMP_TRAPS: 'false'
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"
    command: tail -f /dev/null

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
    container_name: zabbix-web
    ports:
      - "80:8080"
    networks:
      zabbix_network:
        ipv4_address: 172.19.0.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    environment:
      DB_SERVER_HOST: mydatabase.v41.me
      MYSQL_USER: jtxZ3A9A69J2eFgVwp_zabbix
      MYSQL_PASSWORD: jtxZ3A9A69J2eFgVwpJE97beUnuE9MW5xBerSgSaespwrTEYx5qbKgLsNfJqRSXHtmfpHh
      # MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: K9brEwbDsdxtMyGAXV_zabbix
      PHP_TZ: Asia/Tokyo
    depends_on:
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"

networks:
  zabbix_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
