version: '3.5'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:5.4-alpine-latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      DB_SERVER_HOST: mydatabase.v41.me
      MYSQL_USER: jtxZ3A9A69J2eFgVwp_zabbix
      MYSQL_PASSWORD: jtxZ3A9A69J2eFgVwpJE97beUnuE9MW5xBerSgSaespwrTEYx5qbKgLsNfJqRSXHtmfpHh
      MYSQL_DATABASE: K9brEwbDsdxtMyGAXV_zabbix
      ZBX_JAVAGATEWAY_ENABLE: 'false'
      ZBX_ENABLE_SNMP_TRAPS: 'false'
    stop_grace_period: 30s
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"
    networks:
      zabbix_network:
        ipv4_address: 172.19.0.2
    # command: tail -f /dev/null

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:5.4-alpine-latest
    container_name: zabbix-web
    ports:
      - "80:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    environment:
      DB_SERVER_HOST: mydatabase.v41.me
      MYSQL_USER: jtxZ3A9A69J2eFgVwp_zabbix
      MYSQL_PASSWORD: jtxZ3A9A69J2eFgVwpJE97beUnuE9MW5xBerSgSaespwrTEYx5qbKgLsNfJqRSXHtmfpHh
      MYSQL_DATABASE: K9brEwbDsdxtMyGAXV_zabbix
      PHP_TZ: Asia/Tokyo
    depends_on:
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"
    networks:
      zabbix_network:
        ipv4_address: 172.19.0.3

networks:
  zabbix_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
